"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import dsb_client
from dsb_client.api.root_api import RootApi  # noqa: E501


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self):
        self.api = RootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_controller_get_accessible_channels(self):
        """Test case for app_controller_get_accessible_channels

        """
        pass


if __name__ == '__main__':
    unittest.main()
