"""
    Origin Organization I-REC API

    Swagger documentation for the DSB  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dsb_client
from dsb_client.model.create_channel_dto import CreateChannelDto


class TestCreateChannelDto(unittest.TestCase):
    """CreateChannelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateChannelDto(self):
        """Test CreateChannelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateChannelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
