"""
    Origin Organization I-REC API

    Swagger documentation for the DSB  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import dsb_client
from dsb_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_channel_controller_create(self):
        """Test case for channel_controller_create

        """
        pass

    def test_message_controller_get_new_from_channel(self):
        """Test case for message_controller_get_new_from_channel

        """
        pass

    def test_message_controller_publish(self):
        """Test case for message_controller_publish

        """
        pass


if __name__ == '__main__':
    unittest.main()
