"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dsb_client
from dsb_client.model.message_dto import MessageDto


class TestMessageDto(unittest.TestCase):
    """MessageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageDto(self):
        """Test MessageDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
