"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dsb_client
from dsb_client.model.login_data_dto import LoginDataDTO


class TestLoginDataDTO(unittest.TestCase):
    """LoginDataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginDataDTO(self):
        """Test LoginDataDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginDataDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
