"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dsb_client
from dsb_client.model.inline_response503 import InlineResponse503


class TestInlineResponse503(unittest.TestCase):
    """InlineResponse503 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse503(self):
        """Test InlineResponse503"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse503()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
